In [1]:
from nastran.post import read_modal_f06

In [2]:
df = read_modal_f06('test/modal.f06')

In [12]:
df[['MODE','CYCLES']]

    MODE     CYCLES
0    1.0   80.54983
1    2.0  201.10720
2    3.0  201.10720
3    4.0  319.44740
4    5.0  402.20370
5    6.0  402.20370
6    7.0  517.25160
7    8.0  517.25160
8    9.0  683.93400
9   10.0  683.93400
10  11.0  709.82260
11  12.0  795.01680
12  13.0  795.01710
13  14.0  980.90660
14  15.0  980.90660